//
// Generated file, do not edit! Created by opp_msgtool 6.1 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class subtask;
class subtaskResp;
class gossip;
/**
 * Class generated from <tt>message.msg:1</tt> by opp_msgtool.
 * <pre>
 * message subtask
 * {
 *     int sourceId;
 *     int destId;
 *     int queryLen;
 *     int query[];
 *     int TaskNum;
 *     int subTaskNum;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class subtask : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int destId = 0;
    int queryLen = 0;
    int *query = nullptr;
    size_t query_arraysize = 0;
    int TaskNum = 0;
    int subTaskNum = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const subtask& other);

  protected:
    bool operator==(const subtask&) = delete;

  public:
    subtask(const char *name=nullptr, short kind=0);
    subtask(const subtask& other);
    virtual ~subtask();
    subtask& operator=(const subtask& other);
    virtual subtask *dup() const override {return new subtask(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getQueryLen() const;
    virtual void setQueryLen(int queryLen);

    virtual void setQueryArraySize(size_t size);
    virtual size_t getQueryArraySize() const;
    virtual int getQuery(size_t k) const;
    virtual void setQuery(size_t k, int query);
    virtual void insertQuery(size_t k, int query);
    [[deprecated]] void insertQuery(int query) {appendQuery(query);}
    virtual void appendQuery(int query);
    virtual void eraseQuery(size_t k);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual int getSubTaskNum() const;
    virtual void setSubTaskNum(int subTaskNum);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const subtask& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, subtask& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:11</tt> by opp_msgtool.
 * <pre>
 * message subtaskResp
 * {
 *     int sourceId;
 *     int destId;
 *     int answer;
 *     int TaskNum;
 *     int SubTaskNum;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class subtaskResp : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int destId = 0;
    int answer = 0;
    int TaskNum = 0;
    int SubTaskNum = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const subtaskResp& other);

  protected:
    bool operator==(const subtaskResp&) = delete;

  public:
    subtaskResp(const char *name=nullptr, short kind=0);
    subtaskResp(const subtaskResp& other);
    virtual ~subtaskResp();
    subtaskResp& operator=(const subtaskResp& other);
    virtual subtaskResp *dup() const override {return new subtaskResp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getAnswer() const;
    virtual void setAnswer(int answer);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual int getSubTaskNum() const;
    virtual void setSubTaskNum(int SubTaskNum);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const subtaskResp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, subtaskResp& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:20</tt> by opp_msgtool.
 * <pre>
 * message gossip
 * {
 *     int sourceId;
 *     int destId;
 *     int TaskNum;
 *     int TaskResult;
 *     string GossipMsg;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class gossip : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int destId = 0;
    int TaskNum = 0;
    int TaskResult = 0;
    omnetpp::opp_string GossipMsg;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const gossip& other);

  protected:
    bool operator==(const gossip&) = delete;

  public:
    gossip(const char *name=nullptr, short kind=0);
    gossip(const gossip& other);
    virtual ~gossip();
    gossip& operator=(const gossip& other);
    virtual gossip *dup() const override {return new gossip(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual int getTaskResult() const;
    virtual void setTaskResult(int TaskResult);

    virtual const char * getGossipMsg() const;
    virtual void setGossipMsg(const char * GossipMsg);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const gossip& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, gossip& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline subtask *fromAnyPtr(any_ptr ptr) { return check_and_cast<subtask*>(ptr.get<cObject>()); }
template<> inline subtaskResp *fromAnyPtr(any_ptr ptr) { return check_and_cast<subtaskResp*>(ptr.get<cObject>()); }
template<> inline gossip *fromAnyPtr(any_ptr ptr) { return check_and_cast<gossip*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

