[General]
network = myNetwork
**.numClients = 7
#*.clients[*].display = "p=100,100;is=s"
#*.clients[*].@display = "i=block/app"
#*.clients.@display = "b=,,ring"
**.myNetwork.displayString = ""
seed-0-mt=11111
